server:
  port: 8080
spring:
  thymeleaf:
        prefix: classpath:/templates/
logging:
  level:
    org.springframework.security: DEBUG
security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      authorized-grant-types: authorization_code,refresh_token