server:
  port: 8086
  servlet:
    session:
      cookie:
        name: RESOURCE_SESSIONID
logging:
  level:
    org.springframework.security: DEBUG
oauth: #oauth2-server认证授权服务器的url配置，在获取AccessToken以及检测AccessToken中会用到
  token: http://localhost:8080/auth/oauth/token
  check_token: http://localhost:8080/auth/oauth/check_token #检查AccessToken有效性的url(认证授权服务器的url地址),获取 AccessToken 对象
security:
  oauth2:
    client:
      clientId:  client
      clientSecret: 123qwe
      userAuthorizationUri: http://localhost:8080/auth/oauth/authorize
      grant-type: authorization_code
      scope: admin
      access-token-uri: http://localhost:8080/auth/oauth/token
    resource:
      userInfoUri: http://localhost:9005/user
    authorization:
      check-token-access: http://localhost:8080/auth/oauth/check_token
  basic:
    enabled: false