auth-server: http://localhost:8080 # 认证服务器地址
resource-server: http://localhost:8086 # 资源服务器地址
server:
  port: 8085
  servlet:
    session:
      cookie:
        name: RESOURCE_SESSIONID
logging:
  level:
    org.springframework.security: DEBUG
spring:
  main:
    allow-bean-definition-overriding: true
  aop:
    proxy-target-class: true
client:
  resourceServerUrl: ${resource-server}
security:
  sessions: never
  oauth2:
    sso:
      loginPath: /login   # 登录路径
    client:
      client-id: client
      client-secret: 123qwe
      scope: admin
      state: 1
      access-token-uri: ${auth-server}/auth/oauth/token
      user-authorization-uri: ${auth-server}/auth/oauth/authorize
      token-name: oauth_token
      pre-established-redirect-uri: http://localhost:8085/callback
    resource:
      token-info-uri: ${auth-server}/auth/oauth/check_token