auth-server: http://localhost:8080 # 认证服务器地址
server:
  port: 8085
logging:
  level:
    org.springframework.security: DEBUG
security:
  oauth2:
#    sso:
#      loginPath: /login   # 登录路径
    client:
      client-id: client
      client-secret: secret
      scope: admin
      state: 1
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
    resource:
      token-info-uri: ${auth-server}/oauth/check_token
spring:
  main:
    allow-bean-definition-overriding: true